sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.pubring.gpg.enc -out local.pubring.gpg
  -d
env:
  global:
  - secure: ISehBsmUszW1J2MP+8yfe4r6I5YLZwhJrW8h0oZsvEDi7Ex1voJzT1C07hNQWcNdenkGnmNZr1V6L1vT0KIQ6S8f7BDS07elCsVOPtRTXM/s/IuNuANRgiMhZiwHvBbP+dH5an0ICFZZHDLqxAPmpFy/joZse+fKiDzzQHSdhzdRXgtXfJbDPLPnwFBS61yTrv/Q+SCOG0K8XFkKhK0GdhRfob3Nq/6sb6WGU3o1gbKDwgVyDz/MejZ37tBKB4x3DZUgXIkJ4bTqr79rPEBm7xId8rGBUp9WQ5USe7RWLMvXC2l53qKOskjhi/AndBThiqFT0sNXBuMAb3XHDvOqS2UhOfY2ZXz7BEdAZICO7a75Tq/iZhAqfIYNjHQMv6XSq27jr4LxPp9rpYPGF/zL4DqCA+AqnmioWlsmX8zydgN4GdxCpUAexY9qJCEUUW0t7CsQk1rGbPcfwMTjoWTMiLfywrRaksJvXNy0sGUMFvsgz7zRhoG0IB2fnR5eZXPJjB9wtgIzA9cK4qC0CA9YiKxGjL9Y7GZJpT5fqpPZRTlzy9cAZ2H+L3BHnlIcpmM9hsQl+q4Bnkw+Y2YXOqSRSxMwf5lhTBIKqE47fYzIXnjQZAZY2YOb8j7IZQs6syGQfv5LYvFoLNAlgDX6qKQ1f6uY+1S7+XhTlyLthpYpXLI=
  - secure: nc2+S0YTih1+hV16ortmZz7zMFxt6KPAeUsRh10+feuNUF4TB520dqVE+niWczJmiYt8C+3H2jzWo+bPmjnpegEV/oGD1fqX4TE9J+sQoxUakFqXJ+gS8aGXk/JF3Q/r+K1DFVLdCe4og2exDb8LBG+vj0wNnPX5PNR31w4zkA3KRvH9pu6oVy5/Yk4lv6eFKVlAdpbAuAUMirbxQj54AVOWMXhVB3SCyDrp0IrPwSvG7+kuCJTb8cIqfLyPiIFWfs+E5yy2SxHJYayS/tbpwboJkAP73PsTkutvzB3w+2AaCa+bUn7VYdKvqkBrBBeapudwgAOIXUR2N5reRtaymFZU/5f92n55mSKZkqqVvnZglf5w9AEYwuK2YQpdqa7tMy8Y6NC+djbYnrkKm17p/LY1CvvCaoSxoKBUNldvAXAw015QNkITdrlh0ovqpDBsMfJjRxQ1Cv8At6eakFvexcwfitoqQtY+rLZMLD5AQTrwNJCHCgHzRRl++wV6irEPNPlFmYTvhpGiTMQW8a7UCWiJMRLiRguXw3YiUq7cj/WE3MD4duCJ/KXhrG8wed/AFaqPq4+mtkNZfNqELCwJTK+n5u4xwJk9sllrrApndVZ9gftNd7qwCr/ymdn4qyrI21BpL2WBeyi9u6Mk3n8AXwQjXE4CVOxmbNWwBtV/05k=
  - secure: icgfcAbxVVbGaCJCoJcKrBxdRVaLuhRWFnB0GpJQSTTUIN3PL+C8+B90AHbF7vwLN037k5TtPlz6iik8VyohGBP5cyqAyFWaPB8raJngLLGF8tNPCMnd1z0A6s72FPt+U0l2yHyqTf6rqSE80QftZ0yYZJU/MYFoeLfCHkKzmIzE7bx6FZONMQkI9z7JfK+Nh4kW/Br13UymB8dbXeLmkIn3y7TNivrKSuJNd2fBS9valPClL65tAn6HgYYetCiI/IRACurYNtScUA5dpWANjgXlCXmmjaLrBTKYfImKLKeoDrVRXbCzUB4sZXuJc6umQ6giTKjwnKwaNx3urq5tePA++v6WEmqVvP6ya/fUp8VuPK4P1YluJlC7bjeQocAHDRlGOLOS4NwthB+bVEuuomY8B0Wo16cND7M53y5fHESRdBDJ4jFFHvmE5xPBklXTKlCe5HSptceJny+iHjYtj53xwjGrlVDRbQ5WFoDpcLWLwW5kPg4WZOXQDYzOaQu/yGAWKO0Af+lKhZ1Jg5VgWwtNYBL6/K5+jb1Z/qAYURfyilADarOGsir/HK/axy99oCft5iG75yjAoMaYVwZzAXGXYWpGampetWsfFxReLZGERxfD5I194fcDt8/kMB8ZG7Y1IhdpUDJOznB5lUDoHMOea5O+/JgQBJ1Op69TFoM=
script:
- ./sbt ++$TRAVIS_SCALA_VERSION test
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publish-signed;
  fi
notifications:
  email:
    recipients:
    - secure: bnzTZg9H/eLojTv4g6BhQLwofphz+cOtMMx5PudOsspo3p44uk7SlL+/fhPL8gqvC2G7vYD3NlwysGPPn4X7KIJu3DPtjgcMjUuIG8SG55g5uLpUlOoLzl3oHnnfDqnDrK3uptaluKjLuO0BBnrDi02986sw0qy0JYS5IUJeHo3rA9DZzSSDV6qwVJa8tPpxSPhPyO/EfDOj4C7zam8UOZH7UTHRqHUUCshl2SO/A2ArAVCJ4gcRoM0BKU/pCE8C98zSTJAgfWw9DJPJnqQpXd09DjjCJ57jvjcWCNVmShPs/JW+MBXtt8dJj3LMii50OsuVbReJ7UPyAnEaBaId2efyph1aN8yvhz6fCooemC25S1qmyafHrFRRGi8RdUvr5dFXZrOnzqo55wSA0JeJh6o5/e22A7HjV43Rz3V3ZT84DgSOMNpWDVgdyrXlV4V66Y/ZKhYoAxDn5dZzdhTJc0ujS8W5P+KW4ausn54L+sELE1l0embVZXTLywVsJOV8YmioB7EjCqr5Bx8H48g6uHYkctv06B/VdVUUYWZ3S0BJyeXlalUGptvy+qmCdTlILQO+Q5u5SNFgS0ed972DsyyFDX6s6FxbKSc2OGW4FlcF0CJy+0tCLGiepwjo1P2Cs12gcL3ri1ZS9dLwo8s0qI9dBHOFSeXf48j6clIbupU=
    - on_success: always
