sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.pubring.gpg.enc -out local.pubring.gpg
  -d
env:
  global:
  - secure: oc1D8VoHwS3UGcjZhh11jafVViPVR5WE377nbfujU2cDfnrlrQx2aKkUoa/PjCzIBre1DxtJJJ8wFgREcEMF5MOYtr4iFPUxmWOUEH32IcQM6I5C3saqIEw8H1advFeo7IwHWFwRsLrKNgF3Dt+ZDrpZXkXAsqho+Rb72vGIAUcP9tV9+y1aIkRK7yRNtptN4ojRdhpTpJzcdFiPAsv5YEcyVOWASdoB+JUvO02qooYFog/vdJ3MwwKU2BBl1qF1hdc7SFeq+FVfeccvtzmKUWRoMT31q8aL9Dkij/6aybumflSHwSt/nRl92BtTsQaOcmk59QDlVss2rcYiYnns8y/VKEfXXmNgfXby2OL4UEeqUaXtFzMdfOVnN3/nBAKMNZETUyOg5W0B4V7CMBsPuNdkR4D3ixipi8MaCkYr9rWna+ryhXVr5VhrjFugvrnBIUBVM2PzFTo9zZeovOdvWyC4yTYwN/2aVa+o1SIPB2XFY9Fc/yi7oFrK+xSEfU0iwaO3qJRa60W1iJI/TE0RdQizHV8GAet5e8CCdKoZMkzbW+H6MwAEAQQ7m3vwI3F5LYWhiIYaqW2x1CCedDQvkX67MtKYdhx71Wpb+t8YUazyAhtkbO8nMz403IZLEPa3XIWeHjS21VzG3fR3afNY14u5yYYFviV+Ex9+oF9MbFI=
  - secure: NT08X7wocoWaWNZqJohRIi+8AF2cxjF8Iy5lrfcItEV9o7/2u88EP7QfNh3iHhIRJ6TwljW626ofYvhsqKYGCAEqd9Xouyk7ZoK/QmLm8MxmX18x6E82lbgXyISdyIgoNVL8P1ZmBESBeaMZG6pUSMgDcgawNZu1g2lrqcjeQAlOa6G1JRG3wUoKLuaK2yBdsqBgGm8/crOdQeiFD5y8jQ0dvhRxJEdrZUR9ZW8Hrv1V9hgEDKzF06ADwTPjrUbTCV795QIDzWTs8thj6eN8gugEobotsmsgulz1dbDkbCJd1rjeyuhJ/6hiea6F6wwEyFJauogTUAQ3ABtcBGqgj7jsPU0vQb1AnMDz87L3nNq7nF0/YLrjQcnOCjulhsp8tXlpnInPJtMCDGREaAl0/vh1C0NSTUnjYo5+qwkXAorEpIkx/h0UPjODS1rZkGzmAi0yxYlAQ8Lo0xjHgCeQLR4kjTOLfQ49KSduyO1Atl8Cb8UWuZ4WXexSpYiWLOfGbG9loT41fswQ8oddOJ+CVw6jcfqW39K/r4k+paMJleZTFDRPMhKP9dZmznAJvhKGbBFB+4EyHTZR9IE0RicVFEianVuJ/6DrE7eH+VyMu3VDMxPPM+dRzQ0wJziIBNdKeXV/Nuf7BAfV53drooQVM7mawklphqR8sCIpcPmZzis=
  - secure: iISF1Rbe8C3+BUBMy+kziJRoeXLMJLdP0SGXjJ6HpDPEIIG/cshV2kuBlw4K6EJP7al5lFfn9xbaT/oMU/ZYgMBwIz9ZYDhwOJVG9wjIsh6ly9NXIAbo1ubQHuvq2qLJ8xslrW9V6tZyPTKLi+Vikn1NjjfEnnUf/PCw/0zbXgLxbK1DuT9TCkeB399Ze9ueKsEJKa7vWiEvrCt4WvU9qf9c/89SDykoFMoD0D9dlEBev+34aj8XMg1pM4YN2iS+YIBx9R106apKHKSkKxudaA7Bw73Uba9pg1ARHfBwIVkaPK9EXvl7CB6sKuQbyn0VHT+I921GC0qb6NZ+VA+uFWLK69qklo1KwcRmOneh07cUkwmd9I2DWiSy9LZye0+EB3hIqm9k6pE58kroCYFHejsyMojyVRlyqNqbjurNsfPF4+arN5kc3N1WpNXMpPMNlmwJhD/3oRyMGwk4+OHJPrmaxkINofJuGsVTAsxNyvFH1Pm1dnYK19aTJoA5vMKWgImk1xB0SQcqbmWSv+oSFh/nLWv5505419UHwxVJpMYGY/r21QuSVBCnia6yxTdoJb7w0Ua+P5E3yMpvtKOFt12ziU1BZf5/fBWlfKG8s1hae+WQDfKhTKTlKKJ+9towB1/KQp47aG4zSzQ6NMQkTUeMQv/gShTMDkeUEJAoKNU=
script:
  - ./sbt ++$TRAVIS_SCALA_VERSION test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publish-signed; fi
notifications:
  email:
    recipients:
    - secure: bnzTZg9H/eLojTv4g6BhQLwofphz+cOtMMx5PudOsspo3p44uk7SlL+/fhPL8gqvC2G7vYD3NlwysGPPn4X7KIJu3DPtjgcMjUuIG8SG55g5uLpUlOoLzl3oHnnfDqnDrK3uptaluKjLuO0BBnrDi02986sw0qy0JYS5IUJeHo3rA9DZzSSDV6qwVJa8tPpxSPhPyO/EfDOj4C7zam8UOZH7UTHRqHUUCshl2SO/A2ArAVCJ4gcRoM0BKU/pCE8C98zSTJAgfWw9DJPJnqQpXd09DjjCJ57jvjcWCNVmShPs/JW+MBXtt8dJj3LMii50OsuVbReJ7UPyAnEaBaId2efyph1aN8yvhz6fCooemC25S1qmyafHrFRRGi8RdUvr5dFXZrOnzqo55wSA0JeJh6o5/e22A7HjV43Rz3V3ZT84DgSOMNpWDVgdyrXlV4V66Y/ZKhYoAxDn5dZzdhTJc0ujS8W5P+KW4ausn54L+sELE1l0embVZXTLywVsJOV8YmioB7EjCqr5Bx8H48g6uHYkctv06B/VdVUUYWZ3S0BJyeXlalUGptvy+qmCdTlILQO+Q5u5SNFgS0ed972DsyyFDX6s6FxbKSc2OGW4FlcF0CJy+0tCLGiepwjo1P2Cs12gcL3ri1ZS9dLwo8s0qI9dBHOFSeXf48j6clIbupU=
    - on_success: always
