sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in local.pubring.gpg.enc -out local.pubring.gpg
  -d
env:
  global:
  - secure: KluMGl013IFKgGovQ/YXUaH4SSV6ufQCCVDxrXr60CKvCP3Qsjtccl/2uy+U7KirMG1cLJlIGBVCDID2mwSHA0BpZ4CdVZfxv9xoWPJL2AbDm/ZKD9dAMuZb4462GdYDPBNqnsXlY5GLIv4BS5Dl8xrhnkSIcPEtTSuvBEoiIlBfL18C94mUSrkZjxsn1TDZpJWIiJBrAGH2XksUxYphEdv6+AJe6lxGZp1n5WiFYOkLaOJII0JOk4t8jL85VKZXauM1sB83v6xlv6L1ailNL8owBqNx4ltzSfViLjMmKRBvajeLoEcE6D72WMX6S//jou1mHKsnPOl4ED2IPs1vwhC9NHT5itYbd/TvuFCNAyc4Q0Ob87P2nj9uhxijfRD8qW3skeGJtdRP05t+zYiXpHf48ySmirZs/zvT/3J8NqDRZ1sMgFVX4BwW3Gk2a8vnxjgdupp/FMM1j/jrTLJoGL/pef/B3wkUWy03BmV3C2RQOYTDoU+/jRrj9w+E/efb/gKR48D+LCx5lkWJhKiYltccutmprRmazE0Mv2JkSu4gsOWVGJGOZ2qsL+Z70Z3QSQsqJYJ6zWWm5VvvOUgagApPrhJp5JqvU6C1Zi6vuUiuTniok8CEIpB73vmdsCAiEfTUMiXRfgYJK4p8IdGvfQ68xhQKzWLALbXSxEiJLaY=
  - secure: JrWa2UUB/U0Oz3bM4yDTCXBtI0NDHwREc6YhT9jyUjmrlJA8x4XOIRwZymXTBKaMXBm2ZoIfKW0TvNS7OSCHvnsZCqZPoK5WOmh+B8gAOXkurDNAtZftBR0CaY58zeZimr6SJHCRZuVdGC/av3RnKgFAHVBDxPRHSvSVZElSebDgKq9rpOmQ0ebmMcwE3U2ySbZwl9U1aMC6bN6i07IG4GRMMY5qzDLvEXEnwNTnb2fowQgll6a1rWvKTlPdvwG1hwfeqwxxGbRgxbtUHi8h/oKOHFaTfhdCdBfoCJJj2GLdxn8OO4gbu1m9ViHlZeS1yrVNHKqP9PpVk9V1KNADbS6Aa3praXXJV7kBJmeQ2YassE2xjoAD1WM/v57nu4PaOKhIhHtlQ1uNf5XOKqVP5q3TItWUC21dbJJ8urafqJr1dzbwkW2KA5V9Gw7BPfnYwlQVMEJa7YEVHh3+UgfrOgYe66IpFrHOh8RDctvbZ6B0ckS791g5O9kynv0zogLzXoiIU+INP5cfaigEkbMwGDuJhz5qZlDsPZCSiUT55Q7K1/5C5c89ePBBc2xIWqoJ0AlKtJatUnSmZwPsLv/QMIwye35L5bdJWOP0hVD4bgXJsjMC2XSnInO97npbDEDkfPQ1DCODZd3lwV9k6xu06RhRvRjcvRy4OI6S7l5ZouE=
script:
- ./sbt ++$TRAVIS_SCALA_VERSION test
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publish-signed;
  fi
